# -*- coding: utf-8 -*-
"""online-computer-system.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f7knuGtbxnY45TT1Lm61EbaZYK_SKprY
"""

# Define arrays to store item information
case_items = [("A1", "Compact", 75.00), ("A2", "Tower", 150.00)]
ram_items = [("B1", "8 GB", 79.99), ("B2", "16 GB", 149.99), ("B3", "32 GB", 299.99)]
hdd_items = [("C1", "1 TB HDD", 49.99), ("C2", "2 TB HDD", 89.99), ("C3", "4 TB HDD", 129.99)]

# Function to display items and get user input
def choose_item(category, items):
    print(f"\n{category} Items:")
    for code, description, price in items:
        print(f"{code}: {description} - ${price}")

    while True:
        user_input = input(f"Choose a {category} item code: ").upper()
        for code, description, price in items:
            if user_input == code:
                return description, price
        print("Invalid item code. Please try again.")

# Function to calculate computer price
def calculate_price(basic_set_price, case_price, ram_price, hdd_price):
    return basic_set_price + case_price + ram_price + hdd_price

# Main program for Task 1
def task1():
    # Basic set price
    basic_set_price = 200.00

    # Choose main items
    case_description, case_price = choose_item("Case", case_items)
    ram_description, ram_price = choose_item("RAM", ram_items)
    hdd_description, hdd_price = choose_item("Main Hard Disk Drive", hdd_items)

    # Calculate computer price
    total_price = calculate_price(basic_set_price, case_price, ram_price, hdd_price)

    # Output chosen items and total price
    print("\nChosen Items:")
    print(f"Case: {case_description} - ${case_price}")
    print(f"RAM: {ram_description} - ${ram_price}")
    print(f"Main Hard Disk Drive: {hdd_description} - ${hdd_price}")
    print(f"Total Price: ${total_price}")

# Test Task 1
task1()